[300] feat: Race Timer
webdevcody/code-racer pull request #306
Opened 2023-07-16 08:44 UTC by phoukiethseng

---
title: Issue #300  | feat: New Race Timer
---

Discord Username: @phoukiethseng 

## What type of PR is this? (select all that apply)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

- Now no op key won't trigger start timer
- Added new RaceTimer component

## Related Tickets & Documents

- Related Issue #300 
- Closes #300 

## QA Instructions, Screenshots, Recordings

https://github.com/webdevcody/code-racer/assets/57098413/492f6dcc-d979-444f-be25-d707b62bd8fb

### UI accessibility concerns?

## Added/updated tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## [optional] Are there any post deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-16 09:19 UTC, scape76 commented
Cool idea, I think it would be cool if it was an option to see this timer, because some people it will distract imo

2023-07-16 09:26 UTC, phoukiethseng commented
I added a hidden option

2023-07-16 13:27 UTC, webdevcody requested changes

2023-07-16 13:27 UTC, webdevcody commented on src/app/race/race-timer.tsx
> +        setTimeout(() => updateElapsedTime(), updateInterval);
this should be in an useEffect and use the setInterval function to call updateElaspedTime every 100 ms, also be sure to return a cleanup function from the useEffect to clean up the interval.

2023-07-16 16:07 UTC, phoukiethseng commented on src/app/race/race-timer.tsx
> +        setTimeout(() => updateElapsedTime(), updateInterval);
Sorry this is probably a bad implementation but timer only start when `toggle` is true, I try useEffect but it's not working. So I setTimeout on render cycle and let updateElapsedTime mutate `elapsedTime` state thus causing another setTimeout so on and so forth. Once toggle is false, it will not setTimeout thus stopping timer.

2023-07-16 17:06 UTC, fajfara commented on src/app/race/race-timer.tsx
> +        setTimeout(() => updateElapsedTime(), updateInterval);
Hey, just jumping in, are visibility (hidden and toggle) props needed? Couldn't you handle the toggle by not mounting the component in `src/app/race/Race.tsx` ie. `condition && <Timer />`? I Feel like this is an over-engineered stopwatch component 😄

2023-07-17 02:02 UTC, webdevcody approved these changes

2023-07-17 02:27 UTC, merged